{% set version = "3.7.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcdk
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rcdk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rcdk/rcdk_{{ version }}.tar.gz
  sha256: 28bc63cad0e22c9c725bea00e9af573e4bc634590ec2672a941ce85e8c761d1c

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-fingerprint
    - r-iterators
    - r-itertools
    - r-png
    - r-rjava
    - r-rcdklibs >=2.8
  run:
    - r-base
    - r-fingerprint
    - r-iterators
    - r-itertools
    - r-png
    - r-rjava
    - r-rcdklibs >=2.8

test:
  commands:
    - $R -e "library('rcdk')"           # [not win]
    - "\"%R%\" -e \"library('rcdk')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rcdk
  license: LGPL-2.0-or-later
  summary: Allows the user to access functionality in the 'CDK', a Java framework for chemoinformatics. This allows the user to load molecules, evaluate fingerprints, calculate molecular descriptors and so on. In addition, the 'CDK' API allows the user to view structures in 2D.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rcdk
# Version: 3.4.7.1
# Date: 2018-04-29
# Title: Interface to the 'CDK' Libraries
# Authors@R: c(person('Rajarshi', 'Guha', role=c('aut',"cph"), email='rajarshi.guha@gmail.com'), person('Zachary', 'Charlop-Powers', role=c('cre'), email='zach.charlop.powers@gmail.com'), person('Emma', 'Schymanski', role=c('ctb'), email='schymane@gmail.com'))
# Depends: rcdklibs (>= 1.5.12)
# Imports: fingerprint, rJava, methods, png, iterators, itertools
# Suggests: xtable, RUnit, knitr, rmarkdown
# SystemRequirements: Java JDK 8 or higher
# License: LGPL
# LazyLoad: yes
# Description: Allows the user to access functionality in the 'CDK', a Java framework for chemoinformatics. This allows the user to load molecules, evaluate fingerprints, calculate molecular descriptors and so on. In addition, the 'CDK' API allows the user to view structures in 2D.
# RoxygenNote: 6.0.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-09-25 10:11:39 UTC; ripley
# Author: Rajarshi Guha [aut, cph], Zachary Charlop-Powers [cre], Emma Schymanski [ctb]
# Maintainer: ORPHANED
# Repository: CRAN
# Date/Publication: 2018-09-26 05:01:07 UTC
# X-CRAN-Original-Maintainer: Zachary Charlop-Powers <zach.charlop.powers@gmail.com>
# X-CRAN-Comment: Orphaned and corrected on 2018-09-26 as issues with recent Java versions were not corrected despite reminders.
